#!/bin/bash
# Define Neovim applications you want to experiment with.

# The repository cloned must bootstrap itself.  In otherwords, clone and nvim
# is all tha tis needed.
#
# alias      | Github repository       | default or branch name
readonly neovim_distros=(
  "CyberNvim | pgosar/CyberNvim        | default"
  "LazyVim   | LazyVim/starter         | default"
  "OVIwrite  | MiragianCycle/OVIWrite  | default"
  "astro     | AstroNvim/AstroNvim     | default"
  "asyncedd  | asyncedd/dots.nvim      | default"
  "barebones | Traap/barebones         | default"
  "baretmux  | Traap/barebones         | tmux"
  "cam       | ChristianChiarulli/nvim | default"
  "default   | none                    | none"
  "exos      | exosyphon/nvim          | none"
  "kickstart | nvim-lua/kickstart.nvim | default"
  "launch    | LunarVim/Launch.nvim    | default"
  "lervag    | lervag/dotnvim          | default"
  "nvchad    | NvChad/NvChad           | default"
  "nvconf    | TechnicalDC/NvConf      | default"
  "prime     | Traap/init.lua          | default"
  "pwnvim    | pwnwriter/pwnvim        | default"
  "traap     | Traap/nvim              | default"
  "vapour    | Traap/VapourNvim        | default"
  "void      | nvoid-lua/nvoid         | default"
  "xray      | Traap/nvim              | v0.9.5-lazyvim"
  "zero      | Traap/lazy.zero         | default"
  "zulu      | Traap/nvim              | v0.6.8-packer"
)
