#!/bin/bash
# Define Neovim applications you want to experiment with.

# The repository cloned must bootstrap itself.  In otherwords, clone and nvim
# is all tha tis needed.
#
# alias      | Github repository       | default or branch name
readonly neovim_distros=(
  "default    | none                    | none"
  "astro      | AstroNvim/template      | default"
  "asyncedd   | asyncedd/dots.nvim      | default"
  "barebones  | Traap/barebones         | default"
  "barelazy   | Traap/barebones         | lazy"
  "baretmux   | Traap/barebones         | tmux"
  "cam        | ChristianChiarulli/nvim | default"
  "CyberNvim  | pgosar/CyberNvim        | default"
  "exos       | exosyphon/nvim          | none"
  "kickstart  | nvim-lua/kickstart.nvim | default"
  "launch     | LunarVim/Launch.nvim    | default"
  "LazyVim    | LazyVim/starter         | default"
  "lervag     | lervag/dotnvim          | default"
  "NormalNvim | NormalNvim/NormalNvim   | default"
  "nvchad     | NvChad/starter          | default"
  "nvconf     | TechnicalDC/NvConf      | default"
  "OVIwrite   | MiragianCycle/OVIWrite  | default"
  "prime      | Traap/init.lua          | default"
  "pwnvim     | pwnwriter/pwnvim        | default"
  "traap      | Traap/nvim              | default"
  "starter    | lazyvim/starter         | default"
  "vapour     | Traap/VapourNvim        | default"
  "void       | nvoid-lua/nvoid         | default"
  "whiskey    | Traap/nvim              | 706377a"
  "xray       | Traap/nvim              | v0.9.5-lazyvim"
  "zero       | Traap/lazy.zero         | default"
  "zulu       | Traap/nvim              | v0.6.8-packer"
)
