#!/bin/bash
# {{{ Define file locations and internal arrays.

# File name that is overwritten with nvim appname aliases.
readonly nvimcfg="$HOME"/.config/nvims
readonly nvimAppNameFile=$nvimcfg/nvim_appnames
readonly  neovimDistros=$nvimcfg/neovim_distros

# nvapp names extracted from neovim_distros array.
nvapps=()

# -------------------------------------------------------------------------- }}}
# {{{ Source configuration files.
sourceFiles() {

[[ ! -f $neovimDistros ]] && echo "Missing $neovimDistros" && exit

source "$neovimDistros"

}
# -------------------------------------------------------------------------- }}}
# {{{ Determine if a pull is needed.

# shellcheck disable=SC2120
gitcheck() {

  # Git variables used to determine if a pull is needed.
  git fetch
  upstream=${1:-'@{u}'}
  local=$(git rev-parse @)
  remote=$(git rev-parse "$upstream")
  base=$(git merge-base @ "$upstream")

  if [[ "$local" == "$remote" ]]; then
    echo "Up-to-date"
  elif [[ "$remote" == "$base" ]]; then
    echo "Need-to-Push"
  elif [[ "$local" == "$base" ]]; then
    echo "Need-to-Pull"
  else
    echo "Diverged"
  fi
}

# -------------------------------------------------------------------------- }}}
# {{{ Remove all spaces from parameter 1.

removeSpaces() {
  var="$(echo -e "$1" | tr -d '[:space:]')"
  echo "$var"
}

# -------------------------------------------------------------------------- }}}
# {{{ Extract fields from neovim_app array.

buildNeovimAppArray() {
  for fields in "${neovim_distros[@]}"; do
    IFS=$'|' read -r alias _url _branch <<<"$fields"
    alias="$(removeSpaces "$alias")"
    nvapps+=("$alias")
  done
}

# -------------------------------------------------------------------------- }}}
# {{{ Clone or Pull selected nvapp

cloneOrPullNvApp() {
  for fields in "${neovim_distros[@]}"; do
    IFS=$'|' read -r alias url branch <<<"$fields"

    alias="$(removeSpaces "$alias")"
    if [[ "$1" == "$alias" ]]; then
      url="$(removeSpaces "$url")"
      branch="$(removeSpaces "$branch")"
      location=$HOME/.config/$alias
      if [[ -d "$location" ]]; then
        pullRepository "$alias"
      else
        cloneRepository "$alias" "$url" "$branch"
      fi
      return
    fi
  done
}

# -------------------------------------------------------------------------- }}}
# {{{ Pull repository

pullRepository() {
  alias="$1"
  location=$HOME/.config/$alias
  runCommandFromDirectory "$location" "git pull"
}

# -------------------------------------------------------------------------- }}}
# {{{ Clone Repository

cloneRepository() {
  alias="$1"
  url="$2"
  branch="$3"
  location=$HOME/.config/$alias

  # Clear clone depth when a branch is needed.
  if [[ $branch == "default" ]]; then
    git clone --depth 1 https://github.com/"$url" "$location"
  else
    git clone https://github.com/"$url" "$location"
    runCommandFromDirectory "$location" "git checkout $branch"
  fi
}

# -------------------------------------------------------------------------- }}}
# {{{ Recursively remove directory if present.

removeDirIfPresent() {
  if [[ -d "$1" ]]; then
    echo "Removed $1"
    rm -rf "$1"
  fi
}

# -------------------------------------------------------------------------- }}}
# {{{ Delete NvimApp from $HOME/.config directory

deleteNvimApp() {
  for fields in "${neovim_distros[@]}"; do
    IFS=$'|' read -r alias url branch <<<"$fields"

    alias="$(removeSpaces "$alias")"
    if [[ "$1" == "$alias" ]]; then
      echo "Deleting $alias if required."
      removeDirIfPresent "$HOME"/.cache/"$alias"
      removeDirIfPresent "$HOME"/.config/"$alias"
      removeDirIfPresent "$HOME"/.local/share/"$alias"
      removeDirIfPresent "$HOME"/.local/state/"$alias"
      return
    fi
  done
}

# -------------------------------------------------------------------------- }}}
# {{{ Run a command from another directory.

runCommandFromDirectory() {
  location="$1"
  command="$2"

  cd "$location" || return

  if [[ "$(runCommandCheck "$command")" == true ]]; then
    echo "$command"
    $command
  fi

  toWorkingDirectory
}

# -------------------------------------------------------------------------- }}}
# {{{ Avoid unnecessary pull commands.

runCommandCheck() {
  command="$1"
  run_command=true

  if [[ "$command" == "git pull" ]]; then
    if [[ "$(gitcheck)" != "Need-to-Pull" ]]; then
      run_command=false
    fi
  fi

  echo "$run_command"
}

# -------------------------------------------------------------------------- }}}
# {{{ Move to working directory.

toWorkingDirectory() {
  cd "$dir" || (echo "Returning to working directory failed." && exit)
}

# -------------------------------------------------------------------------- }}}
# {{{ Write neovim aliases to a file that can be sourced.

writeAliasesFile() {
  echo "Creating $nvimscfg directory."
  mkdir -p $nvimcfg
  echo "#!/bin/bash" >"$nvimAppNameFile"
  echo "# NVIM_APPNAME aliases" >>"$nvimAppNameFile"
  for nvapp in "${nvapps[@]}"; do
    if [[ "default" != "$nvapp" ]]; then
      echo alias nvim-"${nvapp,,}"=\"NVIM_APPNAME="$nvapp" nvim\" >>"$nvimAppNameFile"
    fi
  done
}

# -------------------------------------------------------------------------- }}}
# {{{ Select Neovim app to switch to.

selectNeovimApp() {
  config=$(
    printf "%s\n" "${nvapps[@]}" |
      fzf --prompt=" Neovim Config  " \
        --height=35% --layout=reverse --border --exit-0
  )

  if [[ -z $config ]]; then
    echo "Nothing selected"
  elif [[ $config == "default" ]]; then
    config=""
  fi
  echo "$config"
}

# -------------------------------------------------------------------------- }}}
# {{{ Get command line arguments.
#     d : delete nvimapp selected
#     h || invalid : display usage
#     Normal nvims operation for anything else

deleteNvimAppFlag=false
while getopts 'dh' option; do
  case "$option" in
    d)
      deleteNvimAppFlag=true
      ;;
    h)
      echo "Usage: nvims [] [-d] [-h]"
      exit 1
      ;;
    *)
      printf "Usage: nvims [] [-d] [-h]\n"
      exit 1
      ;;
  esac
done

# -- ----------------------------------------------------------------------- }}}
# {{{ Main logic

main() {
  # Save current working directory
  dir=$(pwd)

  # Source configuration files
  sourceFiles

  buildNeovimAppArray
  writeAliasesFile
  choice="$(selectNeovimApp)"

  if [[ "$choice" == "Nothing selected" ]]; then
    echo "Invalid choice. Exiting" && exit
  fi

  if [[ $deleteNvimAppFlag == true ]]; then
    deleteNvimApp "$choice"
  else
    cloneOrPullNvApp "$choice"
    NVIM_APPNAME="$choice" nvim "$@"
  fi
}

# -------------------------------------------------------------------------- }}}
main "$@"
